### PR TITLE
Allow lazy loading for all elements

### PR DESCRIPTION
**Pull request by glevhen**

### CODE REVIEW

**Comment by ihorvansach** [comment]
@glevhen , thank you for your contribution. We are not sure that it is a good idea to enable lazyload for all elements as this can bring a performance issue. 

Can you tell me more about why you did this change?

**Comment by glevhen** [comment]
@ihorvansach I didn't know that it can cause performance issue. But if this is true, could you suggest the way to easily extend element selectors without overriding template or at least include `a` element to the selectors (I can create PR)? In my case I need to add background image to the link (element `a`), I think it pretty common case, because `a` with background often use as clickable banners

**Comment by ihorvansach** [comment]
@glevhen , please use this changes
https://github.com/magefan/module-lazyload/commit/7abbf52617716b0dffa3c06480a7255cc633142e

they will be available in the next version, 
So with this you'' available to extend the layout and change the lazy load config via your theme layout

**Comment by glevhen** [comment]
@ihorvansach thank you

**Pull request closed without merging**
